language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
arch:
  - arm64
  - amd64
os:
  - linux
  - osx
  - windows
dist:
  - bionic
  - xenial
  - trusty
  - precise
