language: java
branches:
    only:
      - master
matrix:
    fast_finish: true
    allow_failures:
      - jdk:
          - openjdk9
          - openjdk10
        os:
          - linux
        name: "Linux Java Older"
        arch:
          - arm64
          - amd64
      - jdk:
          - openjdk9
          - openjdk10
        os:
          - osx
        arch:
          - amd64
        name: "Mac Java Older"
      - jdk:
          - openjdk13
          - oraclejdk13
        os:
          - osx
        name: "Mac Java Beta"
        arch:
          - amd64
      - jdk:
          - openjdk13
          - oraclejdk13
        os:
          - linux
        name: "Linux Java Beta"
        arch:
          - arm64
          - amd64
    include:
      - jdk:
          - openjdk11
          - openjdk12
          - oraclejdk11
          - oraclejdk12
          - oraclejdk9
        os:
          - linux
        name: "Linux Java LTS"
        arch:
          - arm64
          - amd64
      - jdk:
          - openjdk11
          - openjdk12
          - oraclejdk11
          - oraclejdk12
          - oraclejdk9
        os:
          - osx
        name: "Mac Java LTS"
        arch:
          - amd64
          - arm64
